name: Repina-ui CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install > /dev/null
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod --cross-origin=use-credentials
    - run: ng run repina:server:production

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "dist/browser/"
        target: "/home/repina/repina_branding/front/browser/"
        strip_components: 2
  
    - name: copy server file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "dist/server/"
        target: "/home/repina/repina_branding/front/server/"
        strip_components: 2
    
    - name: restart ssr systemd
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: systemctl restart ssr
